# This is a basic workflow to help you get started with Actions

name: terraform pipeline

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
    #branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  terraform:
    # The type of runner that the job will run on
    name: 'Terraform'
    runs-on: ubuntu-latest
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Downloading AWS CLI
        run: wget "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
        
      - name: unzip aws cli
        run: unzip awscli-exe-linux-x86_64.zip
        
      - name: changing directory
        run: ./aws/install
        
      - name: checking aws version
        run: aws --version
